### ISSUE TITLE
Error during pip install -e .

### ISSUE THREAD

**Issue by oscar6echo** [jupyterlab/mimerender-cookiecutter-ts#30]
Just tried the cookie cutter in the conda env defined in https://github.com/jupyterlab/extension-examples.

It breaks at `pip install -e .`.   
See logs below.  

How to fix this ?

```
❯ pip install -e .
Obtaining file:///home/olivier/GDrive/dev/jupyterlab-explo/jupyterlab_graphviz
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
ERROR: Exception:
Traceback (most recent call last):
  File "/home/olivier/miniconda3/envs/jlab-ext-examples/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/olivier/miniconda3/envs/jlab-ext-examples/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/home/olivier/miniconda3/envs/jlab-ext-examples/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 339, in run
    requirement_set = resolver.resolve(
  File "/home/olivier/miniconda3/envs/jlab-ext-examples/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 75, in resolve
    collected = self.factory.collect_root_requirements(root_reqs)
  File "/home/olivier/miniconda3/envs/jlab-ext-examples/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 506, in collect_root_requirements
    req = self._make_requirement_from_install_req(
  File "/home/olivier/miniconda3/envs/jlab-ext-examples/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 468, in _make_requirement_from_install_req
    cand = self._make_candidate_from_link(
  File "/home/olivier/miniconda3/envs/jlab-ext-examples/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 188, in _make_candidate_from_link
    self._editable_candidate_cache[link] = EditableCandidate(
  File "/home/olivier/miniconda3/envs/jlab-ext-examples/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 313, in __init__
    super().__init__(
  File "/home/olivier/miniconda3/envs/jlab-ext-examples/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 158, in __init__
    self.dist = self._prepare()
  File "/home/olivier/miniconda3/envs/jlab-ext-examples/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 227, in _prepare
    dist = self._prepare_distribution()
  File "/home/olivier/miniconda3/envs/jlab-ext-examples/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 323, in _prepare_distribution
    return self._factory.preparer.prepare_editable_requirement(self._ireq)
  File "/home/olivier/miniconda3/envs/jlab-ext-examples/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 609, in prepare_editable_requirement
    dist = _get_prepared_distribution(
  File "/home/olivier/miniconda3/envs/jlab-ext-examples/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 58, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/home/olivier/miniconda3/envs/jlab-ext-examples/lib/python3.10/site-packages/pip/_internal/distributions/sdist.py", line 43, in prepare_distribution_metadata
    self.req.isolated_editable_sanity_check()
  File "/home/olivier/miniconda3/envs/jlab-ext-examples/lib/python3.10/site-packages/pip/_internal/req/req_install.py", line 488, in isolated_editable_sanity_check
    and not self.supports_pyproject_editable()
  File "/home/olivier/miniconda3/envs/jlab-ext-examples/lib/python3.10/site-packages/pip/_internal/req/req_install.py", line 229, in supports_pyproject_editable
    return "build_editable" in self.pep517_backend._supported_features()
  File "/home/olivier/miniconda3/envs/jlab-ext-examples/lib/python3.10/site-packages/pip/_vendor/pep517/wrappers.py", line 159, in _supported_features
    return self._call_hook('_supported_features', {})
  File "/home/olivier/miniconda3/envs/jlab-ext-examples/lib/python3.10/site-packages/pip/_vendor/pep517/wrappers.py", line 332, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pep517.wrappers.BackendUnavailable: Traceback (most recent call last):
  File "/home/olivier/miniconda3/envs/jlab-ext-examples/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 89, in _build_backend
    obj = import_module(mod_path)
  File "/home/olivier/miniconda3/envs/jlab-ext-examples/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/tmp/pip-build-env-iggnieuw/overlay/lib/python3.10/site-packages/jupyter_packaging/__init__.py", line 6, in <module>
    from .setupbase import *
  File "/tmp/pip-build-env-iggnieuw/overlay/lib/python3.10/site-packages/jupyter_packaging/setupbase.py", line 37, in <module>
    from setuptools.config import StaticModule
ImportError: cannot import name 'StaticModule' from 'setuptools.config' (/tmp/pip-build-env-iggnieuw/overlay/lib/python3.10/site-packages/setuptools/config/__init__.py)
```

**Comment by timkpaine** [comment]
@oscar6echo upgrade your version of setuptools, there was a backwards incompatible release https://github.com/jupyter/jupyter-packaging/issues/130

**Comment by oscar6echo** [comment]
@timkpaine Thx for the swift reply.

Yes, I have traced down the problem to these lines in `jupyter_packaging/setupbase.py`:
```py
try:
    from setuptools.config import StaticModule
except ImportError:
    # setuptools>=61.0.0
    from setuptools.config.expand import StaticModule
```

In my conda env the packages are all updated:

```sh
❯ conda list jupyter-packaging
# packages in environment at /home/olivier/miniconda3/envs/jlab-ext-examples:
#
# Name                    Version                   Build  Channel
jupyter-packaging         0.12.0             pyhd8ed1ab_0    conda-forge
❯ conda list pip
# packages in environment at /home/olivier/miniconda3/envs/jlab-ext-examples:
#
# Name                    Version                   Build  Channel
pip                       22.1               pyhd8ed1ab_0    conda-forge
❯ conda list setuptools
# packages in environment at /home/olivier/miniconda3/envs/jlab-ext-examples:
#
# Name                    Version                   Build  Channel
setuptools                62.2.0          py310hff52083_0    conda-forge
```

But where I run `pip install --no-clean -e .` it still breaks as I mentionned above.  
The reason is that in the /tmp/pip-build-env-XXX I see in /overlay/lib/python3.10/jupyter_packaging/setupbase.py I see:
```py
from setuptools.config import StaticModule
[...]
__version__ = '0.10.6'
```

For some unknown (and annoying) reason pip uses an outdated version in the build process while all is up to date in my working env. I imagine there must be some config somewhere to correct that ?

Even more intringuing: Where I `pip install -e .` the hello world example from https://github.com/jupyterlab/extension-examples I see no such error, though I am in the SAME env.....

**Comment by fcollonval** [comment]
Thanks for reporting @oscar6echo, you can look at #31 to correct your extension to fix the issue.

**Comment by oscar6echo** [comment]
@fcollonval thx for the swift fix. It works now overhere.

I realize now that I failed to notice the difference between [hello-world//pyproject.toml](https://github.com/jupyterlab/extension-examples/blob/master/hello-world/pyproject.toml) and  [mimerender-cookiecutter-ts//pyproject.toml](https://github.com/jupyterlab/mimerender-cookiecutter-ts/blob/master/%7B%7Bcookiecutter.python_name%7D%7D/pyproject.toml). This minor version has a big impact !
